name: bachat_gat
description: Manage Saving Group (बचत गट) transactions

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  sqflite_common_ffi_web: ^0.4.5+4
  uuid: ^4.5.1
  json_annotation: ^4.9.0
#  file_saver: ^0.2.14
  file_picker: ^8.3.1
  shared_preferences: ^2.5.1
  pdf: ^3.11.2
  printing: ^5.14.0
  excel: ^4.0.6
  open_file: ^3.5.10
  cross_file: ^0.3.4+2
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3
  build_runner: ^2.4.14

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
