// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq7HqAAB3ZWNjO993Gt-a6QNFbw_vSBfY',
    appId: '1:1089445798939:web:54a17f777992b8893344be',
    messagingSenderId: '1089445798939',
    projectId: 'dev-pratikm-project',
    authDomain: 'dev-pratikm-project.firebaseapp.com',
    storageBucket: 'dev-pratikm-project.appspot.com',
    measurementId: 'G-20LFF24H8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSJT0J_C4fv_LXKCFPfApIvfz7gq2IvXQ',
    appId: '1:1089445798939:android:74f628c1ed52d3d33344be',
    messagingSenderId: '1089445798939',
    projectId: 'dev-pratikm-project',
    storageBucket: 'dev-pratikm-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFpYWKKMyok0He3YPftUi1guRwnhsyhOw',
    appId: '1:1089445798939:ios:0b966a6f94d1d7e63344be',
    messagingSenderId: '1089445798939',
    projectId: 'dev-pratikm-project',
    storageBucket: 'dev-pratikm-project.appspot.com',
    iosBundleId: 'dev.pratikm.bachatGat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFpYWKKMyok0He3YPftUi1guRwnhsyhOw',
    appId: '1:1089445798939:ios:0b966a6f94d1d7e63344be',
    messagingSenderId: '1089445798939',
    projectId: 'dev-pratikm-project',
    storageBucket: 'dev-pratikm-project.appspot.com',
    iosBundleId: 'dev.pratikm.bachatGat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq7HqAAB3ZWNjO993Gt-a6QNFbw_vSBfY',
    appId: '1:1089445798939:web:8a7550a05168a5813344be',
    messagingSenderId: '1089445798939',
    projectId: 'dev-pratikm-project',
    authDomain: 'dev-pratikm-project.firebaseapp.com',
    storageBucket: 'dev-pratikm-project.appspot.com',
    measurementId: 'G-X8RWHNZ6JP',
  );

}